name: Build Project

on: [push]

env:
  NODE_VERSION: 14
  CHATGPT_SERVER_URL: ${{ secrets.CHATGPT_SERVER_URL }}
  TOKEN_DEEPGRAM: ${{ secrets.TOKEN_DEEPGRAM }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          CHATGPT_SERVER_URL=${CHATGPT_SERVER_URL} TOKEN_DEEPGRAM=${TOKEN_DEEPGRAM} npm run build
